---
title: "Kickstarter"
author: "Blake Brown and Jacob Fullerton"
date: "12/3/2018"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r Library Packages}
library(tidyverse)
library(readr)
library(caret)
library(keras)
```


```{r Import data}

data <- read_csv("data.csv")

data <- data %>% mutate(state=ifelse(state == 'canceled', 'failed', state))
data <- data %>% mutate(state=ifelse(state == 'live', 'successful', state))
data <- data %>% mutate(state=ifelse(state == 'suspended', 'failed', state))
data <- data %>% filter(state!='undefined')
#NHIS <- NHIS %>% mutate(SEX=ifelse(as.factor(SEX) == 1, 'MALE', 'FEMALE'))
data <- data[2:15]
data$state <- as.factor(data$state)
data$category <- as.factor(data$category)
data$main_category <- as.factor(data$main_category)
data$currency <- as.factor(data$currency)
data$country <- as.factor(data$country)
summary(data)
```



```{r}
set.seed(124)
ind <- createDataPartition(data$state, p=0.8, list = FALSE)
x_train <- data[ind,-9]
x_train_label <- data[ind,9]
x_test <- data[-ind,9]
x_test_label <- data[-ind,9]
#x_train_label <- as.factor(x_train_label)
#x_test_label <- as.factor(x_test_label)

```



```{r}
'
# Normalize training data
x_train <- scale(x_train) 

# Use means and standard deviations from training set to normalize test set
col_means_train <- attr(x_train, "scaled:center") 
col_stddevs_train <- attr(x_train, "scaled:scale")
x_test <- scale(x_test, center = col_means_train, scale = col_stddevs_train)
'
```

Now we define our model (using keras syntax):

```{r}
network <- keras_model_sequential() %>% layer_dense(units = 12, activation = "relu", input_shape = dim(x_train)[2]) %>% layer_dense(units = 8, activation = "relu") %>% layer_dense(units = 8, activation = "relu") %>%layer_dense(units = 8, activation = "relu") %>%layer_dense(units = 8, activation = "relu") %>%layer_dense(units = 1, activation = "sigmoid")

```

Now we need to compile our model, determining our optimizer (e.g., gradient descent), our loss function (e.g., sum of squared error) and the metric by which to measure our performance (e.g., accuracy)

```{r}
network %>% compile(loss = "binary_crossentropy", optimizer = optimizer_adam(lr = 0.0001), metrics = c("binary_accuracy"))

```

Now we fit the model:

```{r}
'
x_train <- as.matrix(x_train)
x_train_label <- as.matrix(x_train_label)
network %>% fit(x_train,x_train_label, epochs = 50, batch_size=5)
'
```
